#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.upload = true
    args.public_library = true

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f5a1739.name = "0.6.21~ynh2"
